name: festim-surface-kinetics-vv-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib=3.8.3
  - numpy<1.25
  - scipy==1.12.0
  - sympy
  - scipy
  - nbconvert
  - ipykernel  # needed to run jupyter notebooks
  - pip:
    - festim==1.3
    - h-transport-materials==0.16
    - pypalettes
    - matplotx
    - pyenergydiagrams
